[package]
name = "rust_decafo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
oauth2 = "4.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"